spring.application.name=bloomlish_backend
spring.datasource.url=jdbc:postgresql://localhost:5432/bloomlish_backend
spring.datasource.username=db_user
spring.datasource.password=db_password
spring.jpa.properties.hibernate.default_schema=uygulama
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.format_sql= true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# create and drop table, good for testing, production set to none or comment it
spring.jpa.hibernate.ddl-auto=update

#Spring konfigürasyon anahtar?
jwt.secret.key=xSSxakURlWuEEfjeVMefX3Gioc/vznLIzlSgFqskNCQ=


