spring.application.name=bloomlish_backend

server.port=${PORT:8080}

# Profil seçimi (default = dev)
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.security=DEBUG
