spring.application.name=bloomlish_backend

server.port=${PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql= true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# create and drop table, good for testing, production set to none or comment it
spring.jpa.hibernate.ddl-auto=update

#Spring konfigürasyon anahtar?
jwt.secret.key=${JWT_SECRET}

quizapi.key=${QUIZ_API_KEY}
quizapi.url=https://quizapi.io/api/v1/questions

iyzico.apiKey=${IYZI_API_KEY}
iyzico.secretKey=${IYZI_SECRET_KEY}
iyzico.baseUrl=https://sandbox-api.iyzipay.com



