spring.datasource.url=jdbc:postgresql://localhost:5432/bloomlish_backend
spring.datasource.username=db_user
spring.datasource.password=db_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update


jwt.secret.key=xSSxakURLWuEEfjeVMefX3Gioc/vznLIzlSgFgskNCQ=

quizapi.key=local-quiz-key

iyzico.apiKey=local-iyzi
iyzico.secretKey=local-iyzi-secret
iyzico.baseUrl=https://sandbox-api.iyzipay.com
