spring.datasource.url=jdbc:postgresql://localhost:5432/bloomlish_backend
spring.datasource.username=db_user
spring.datasource.password=db_password
spring.jpa.properties.hibernate.default_schema=uygulama

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update


jwt.secret.key=xSSxakURLWuEEfjeVMefX3Gioc/vznLIzlSgFgskNCQ=

quizapi.key=local-quiz-key

iyzico.apiKey=sandbox-e1sBpJ3YP38Z2F9TV5wBET0EUBIPa2o4
iyzico.secretKey=sandbox-ChYVofvMvdNRU8QWBs2zN52llioMqFXy
iyzico.baseUrl=https://sandbox-api.iyzipay.com
